// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: object.proto
// Protobuf C++ Version: 5.29.5

#ifndef object_2eproto_2epb_2eh
#define object_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_object_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_object_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_object_2eproto;
namespace Object {
class Chunk;
struct ChunkDefaultTypeInternal;
extern ChunkDefaultTypeInternal _Chunk_default_instance_;
class Object;
struct ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
}  // namespace Object
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Object {
enum ObjectType : int {
  OBJ_INT = 0,
  OBJ_FLOAT = 1,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ObjectType_IsValid(int value);
extern const uint32_t ObjectType_internal_data_[];
constexpr ObjectType ObjectType_MIN = static_cast<ObjectType>(0);
constexpr ObjectType ObjectType_MAX = static_cast<ObjectType>(1);
constexpr int ObjectType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
ObjectType_descriptor();
template <typename T>
const std::string& ObjectType_Name(T value) {
  static_assert(std::is_same<T, ObjectType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ObjectType_Name().");
  return ObjectType_Name(static_cast<ObjectType>(value));
}
template <>
inline const std::string& ObjectType_Name(ObjectType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ObjectType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool ObjectType_Parse(absl::string_view name, ObjectType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectType>(
      ObjectType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Object final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Object.Object) */ {
 public:
  inline Object() : Object(nullptr) {}
  ~Object() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Object* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Object));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Object(
      ::google::protobuf::internal::ConstantInitialized);

  inline Object(const Object& from) : Object(nullptr, from) {}
  inline Object(Object&& from) noexcept
      : Object(nullptr, std::move(from)) {}
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  inline Object& operator=(Object&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Object& default_instance() {
    return *internal_default_instance();
  }
  enum LiteralCase {
    kLiteralInt = 2,
    kLiteralFloat = 3,
    LITERAL_NOT_SET = 0,
  };
  static inline const Object* internal_default_instance() {
    return reinterpret_cast<const Object*>(
        &_Object_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Object& a, Object& b) { a.Swap(&b); }
  inline void Swap(Object* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Object* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Object* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Object>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Object& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Object& from) { Object::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Object* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Object.Object"; }

 protected:
  explicit Object(::google::protobuf::Arena* arena);
  Object(::google::protobuf::Arena* arena, const Object& from);
  Object(::google::protobuf::Arena* arena, Object&& from) noexcept
      : Object(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectTypeFieldNumber = 1,
    kLiteralIntFieldNumber = 2,
    kLiteralFloatFieldNumber = 3,
  };
  // .Object.ObjectType object_type = 1;
  void clear_object_type() ;
  ::Object::ObjectType object_type() const;
  void set_object_type(::Object::ObjectType value);

  private:
  ::Object::ObjectType _internal_object_type() const;
  void _internal_set_object_type(::Object::ObjectType value);

  public:
  // int64 literal_int = 2;
  bool has_literal_int() const;
  void clear_literal_int() ;
  ::int64_t literal_int() const;
  void set_literal_int(::int64_t value);

  private:
  ::int64_t _internal_literal_int() const;
  void _internal_set_literal_int(::int64_t value);

  public:
  // double literal_float = 3;
  bool has_literal_float() const;
  void clear_literal_float() ;
  double literal_float() const;
  void set_literal_float(double value);

  private:
  double _internal_literal_float() const;
  void _internal_set_literal_float(double value);

  public:
  void clear_literal();
  LiteralCase literal_case() const;
  // @@protoc_insertion_point(class_scope:Object.Object)
 private:
  class _Internal;
  void set_has_literal_int();
  void set_has_literal_float();
  inline bool has_literal() const;
  inline void clear_has_literal();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Object& from_msg);
    int object_type_;
    union LiteralUnion {
      constexpr LiteralUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::int64_t literal_int_;
      double literal_float_;
    } literal_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_object_2eproto;
};
// -------------------------------------------------------------------

class Chunk final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Object.Chunk) */ {
 public:
  inline Chunk() : Chunk(nullptr) {}
  ~Chunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Chunk* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Chunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Chunk(
      ::google::protobuf::internal::ConstantInitialized);

  inline Chunk(const Chunk& from) : Chunk(nullptr, from) {}
  inline Chunk(Chunk&& from) noexcept
      : Chunk(nullptr, std::move(from)) {}
  inline Chunk& operator=(const Chunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chunk& operator=(Chunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chunk* internal_default_instance() {
    return reinterpret_cast<const Chunk*>(
        &_Chunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Chunk& a, Chunk& b) { a.Swap(&b); }
  inline void Swap(Chunk* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chunk* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Chunk* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Chunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Chunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Chunk& from) { Chunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Chunk* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Object.Chunk"; }

 protected:
  explicit Chunk(::google::protobuf::Arena* arena);
  Chunk(::google::protobuf::Arena* arena, const Chunk& from);
  Chunk(::google::protobuf::Arena* arena, Chunk&& from) noexcept
      : Chunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kConstantsFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // repeated .Object.Object constants = 2;
  int constants_size() const;
  private:
  int _internal_constants_size() const;

  public:
  void clear_constants() ;
  ::Object::Object* mutable_constants(int index);
  ::google::protobuf::RepeatedPtrField<::Object::Object>* mutable_constants();

  private:
  const ::google::protobuf::RepeatedPtrField<::Object::Object>& _internal_constants() const;
  ::google::protobuf::RepeatedPtrField<::Object::Object>* _internal_mutable_constants();
  public:
  const ::Object::Object& constants(int index) const;
  ::Object::Object* add_constants();
  const ::google::protobuf::RepeatedPtrField<::Object::Object>& constants() const;
  // bytes code = 1;
  void clear_code() ;
  const std::string& code() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_code(Arg_&& arg, Args_... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* value);

  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(
      const std::string& value);
  std::string* _internal_mutable_code();

  public:
  // @@protoc_insertion_point(class_scope:Object.Chunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Chunk& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Object::Object > constants_;
    ::google::protobuf::internal::ArenaStringPtr code_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_object_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Object

// .Object.ObjectType object_type = 1;
inline void Object::clear_object_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_type_ = 0;
}
inline ::Object::ObjectType Object::object_type() const {
  // @@protoc_insertion_point(field_get:Object.Object.object_type)
  return _internal_object_type();
}
inline void Object::set_object_type(::Object::ObjectType value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:Object.Object.object_type)
}
inline ::Object::ObjectType Object::_internal_object_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Object::ObjectType>(_impl_.object_type_);
}
inline void Object::_internal_set_object_type(::Object::ObjectType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_type_ = value;
}

// int64 literal_int = 2;
inline bool Object::has_literal_int() const {
  return literal_case() == kLiteralInt;
}
inline void Object::set_has_literal_int() {
  _impl_._oneof_case_[0] = kLiteralInt;
}
inline void Object::clear_literal_int() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralInt) {
    _impl_.literal_.literal_int_ = ::int64_t{0};
    clear_has_literal();
  }
}
inline ::int64_t Object::literal_int() const {
  // @@protoc_insertion_point(field_get:Object.Object.literal_int)
  return _internal_literal_int();
}
inline void Object::set_literal_int(::int64_t value) {
  if (literal_case() != kLiteralInt) {
    clear_literal();
    set_has_literal_int();
  }
  _impl_.literal_.literal_int_ = value;
  // @@protoc_insertion_point(field_set:Object.Object.literal_int)
}
inline ::int64_t Object::_internal_literal_int() const {
  if (literal_case() == kLiteralInt) {
    return _impl_.literal_.literal_int_;
  }
  return ::int64_t{0};
}

// double literal_float = 3;
inline bool Object::has_literal_float() const {
  return literal_case() == kLiteralFloat;
}
inline void Object::set_has_literal_float() {
  _impl_._oneof_case_[0] = kLiteralFloat;
}
inline void Object::clear_literal_float() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralFloat) {
    _impl_.literal_.literal_float_ = 0;
    clear_has_literal();
  }
}
inline double Object::literal_float() const {
  // @@protoc_insertion_point(field_get:Object.Object.literal_float)
  return _internal_literal_float();
}
inline void Object::set_literal_float(double value) {
  if (literal_case() != kLiteralFloat) {
    clear_literal();
    set_has_literal_float();
  }
  _impl_.literal_.literal_float_ = value;
  // @@protoc_insertion_point(field_set:Object.Object.literal_float)
}
inline double Object::_internal_literal_float() const {
  if (literal_case() == kLiteralFloat) {
    return _impl_.literal_.literal_float_;
  }
  return 0;
}

inline bool Object::has_literal() const {
  return literal_case() != LITERAL_NOT_SET;
}
inline void Object::clear_has_literal() {
  _impl_._oneof_case_[0] = LITERAL_NOT_SET;
}
inline Object::LiteralCase Object::literal_case() const {
  return Object::LiteralCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Chunk

// bytes code = 1;
inline void Chunk::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.ClearToEmpty();
}
inline const std::string& Chunk::code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Chunk.code)
  return _internal_code();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Chunk::set_code(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Object.Chunk.code)
}
inline std::string* Chunk::mutable_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:Object.Chunk.code)
  return _s;
}
inline const std::string& Chunk::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_.Get();
}
inline void Chunk::_internal_set_code(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.Set(value, GetArena());
}
inline std::string* Chunk::_internal_mutable_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.code_.Mutable( GetArena());
}
inline std::string* Chunk::release_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Object.Chunk.code)
  return _impl_.code_.Release();
}
inline void Chunk::set_allocated_code(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Chunk.code)
}

// repeated .Object.Object constants = 2;
inline int Chunk::_internal_constants_size() const {
  return _internal_constants().size();
}
inline int Chunk::constants_size() const {
  return _internal_constants_size();
}
inline void Chunk::clear_constants() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.constants_.Clear();
}
inline ::Object::Object* Chunk::mutable_constants(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Object.Chunk.constants)
  return _internal_mutable_constants()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Object::Object>* Chunk::mutable_constants()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Object.Chunk.constants)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_constants();
}
inline const ::Object::Object& Chunk::constants(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Chunk.constants)
  return _internal_constants().Get(index);
}
inline ::Object::Object* Chunk::add_constants() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Object::Object* _add = _internal_mutable_constants()->Add();
  // @@protoc_insertion_point(field_add:Object.Chunk.constants)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Object::Object>& Chunk::constants() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Object.Chunk.constants)
  return _internal_constants();
}
inline const ::google::protobuf::RepeatedPtrField<::Object::Object>&
Chunk::_internal_constants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.constants_;
}
inline ::google::protobuf::RepeatedPtrField<::Object::Object>*
Chunk::_internal_mutable_constants() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.constants_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Object


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Object::ObjectType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Object::ObjectType>() {
  return ::Object::ObjectType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // object_2eproto_2epb_2eh
