// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: object.proto
// Protobuf C++ Version: 5.29.5

#include "object.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Object {

inline constexpr Object::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : object_type_{static_cast< ::Object::ObjectType >(0)},
        literal_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Object::Object(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObjectDefaultTypeInternal() {}
  union {
    Object _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObjectDefaultTypeInternal _Object_default_instance_;

inline constexpr Chunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : constants_{},
        code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Chunk::Chunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChunkDefaultTypeInternal() {}
  union {
    Chunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChunkDefaultTypeInternal _Chunk_default_instance_;
}  // namespace Object
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_object_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_object_2eproto = nullptr;
const ::uint32_t
    TableStruct_object_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Object::Object, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_.object_type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_.literal_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_.constants_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Object::Object)},
        {14, -1, -1, sizeof(::Object::Chunk)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Object::_Object_default_instance_._instance,
    &::Object::_Chunk_default_instance_._instance,
};
const char descriptor_table_protodef_object_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014object.proto\022\006Object\"\233\001\n\006Object\022\'\n\013obj"
    "ect_type\030\001 \001(\0162\022.Object.ObjectType\022\025\n\013li"
    "teral_int\030\002 \001(\003H\000\022\027\n\rliteral_float\030\003 \001(\001"
    "H\000\022\026\n\014literal_bool\030\004 \001(\010H\000\022\025\n\013literal_ni"
    "l\030\005 \001(\tH\000B\t\n\007literal\"8\n\005Chunk\022\014\n\004code\030\001 "
    "\001(\014\022!\n\tconstants\030\002 \003(\0132\016.Object.Object*C"
    "\n\nObjectType\022\013\n\007OBJ_INT\020\000\022\r\n\tOBJ_FLOAT\020\001"
    "\022\014\n\010OBJ_BOOL\020\002\022\013\n\007OBJ_NIL\020\003B\004Z\002./b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_object_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_object_2eproto = {
    false,
    false,
    321,
    descriptor_table_protodef_object_2eproto,
    "object.proto",
    &descriptor_table_object_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_object_2eproto::offsets,
    file_level_enum_descriptors_object_2eproto,
    file_level_service_descriptors_object_2eproto,
};
namespace Object {
const ::google::protobuf::EnumDescriptor* ObjectType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_object_2eproto);
  return file_level_enum_descriptors_object_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ObjectType_internal_data_[] = {
    262144u, 0u, };
bool ObjectType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class Object::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_._oneof_case_);
};

Object::Object(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Object)
}
inline PROTOBUF_NDEBUG_INLINE Object::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Object& from_msg)
      : literal_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Object::Object(
    ::google::protobuf::Arena* arena,
    const Object& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Object* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.object_type_ = from._impl_.object_type_;
  switch (literal_case()) {
    case LITERAL_NOT_SET:
      break;
      case kLiteralInt:
        _impl_.literal_.literal_int_ = from._impl_.literal_.literal_int_;
        break;
      case kLiteralFloat:
        _impl_.literal_.literal_float_ = from._impl_.literal_.literal_float_;
        break;
      case kLiteralBool:
        _impl_.literal_.literal_bool_ = from._impl_.literal_.literal_bool_;
        break;
      case kLiteralNil:
        new (&_impl_.literal_.literal_nil_) decltype(_impl_.literal_.literal_nil_){arena, from._impl_.literal_.literal_nil_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Object.Object)
}
inline PROTOBUF_NDEBUG_INLINE Object::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : literal_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Object::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.object_type_ = {};
}
Object::~Object() {
  // @@protoc_insertion_point(destructor:Object.Object)
  SharedDtor(*this);
}
inline void Object::SharedDtor(MessageLite& self) {
  Object& this_ = static_cast<Object&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_literal()) {
    this_.clear_literal();
  }
  this_._impl_.~Impl_();
}

void Object::clear_literal() {
// @@protoc_insertion_point(one_of_clear_start:Object.Object)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (literal_case()) {
    case kLiteralInt: {
      // No need to clear
      break;
    }
    case kLiteralFloat: {
      // No need to clear
      break;
    }
    case kLiteralBool: {
      // No need to clear
      break;
    }
    case kLiteralNil: {
      _impl_.literal_.literal_nil_.Destroy();
      break;
    }
    case LITERAL_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = LITERAL_NOT_SET;
}


inline void* Object::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Object(arena);
}
constexpr auto Object::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Object),
                                            alignof(Object));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Object::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Object_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Object::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Object>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Object::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Object>(), &Object::ByteSizeLong,
            &Object::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Object, _impl_._cached_size_),
        false,
    },
    &Object::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Object::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 5, 0, 33, 2> Object::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Object>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Object.ObjectType object_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Object, _impl_.object_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Object, _impl_.object_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Object.ObjectType object_type = 1;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.object_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int64 literal_int = 2;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_int_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // double literal_float = 3;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_float_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // bool literal_bool = 4;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_bool_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // string literal_nil = 5;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_nil_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\0\0\0\13\0\0"
    "Object.Object"
    "literal_nil"
  }},
};

PROTOBUF_NOINLINE void Object::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Object)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.object_type_ = 0;
  clear_literal();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Object::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Object& this_ = static_cast<const Object&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Object::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Object& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Object)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .Object.ObjectType object_type = 1;
          if (this_._internal_object_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_object_type(), target);
          }

          switch (this_.literal_case()) {
            case kLiteralInt: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt64ToArrayWithField<2>(
                      stream, this_._internal_literal_int(), target);
              break;
            }
            case kLiteralFloat: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                  3, this_._internal_literal_float(), target);
              break;
            }
            case kLiteralBool: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteBoolToArray(
                  4, this_._internal_literal_bool(), target);
              break;
            }
            case kLiteralNil: {
              const std::string& _s = this_._internal_literal_nil();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Object.Object.literal_nil");
              target = stream->WriteStringMaybeAliased(5, _s, target);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Object)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Object::ByteSizeLong(const MessageLite& base) {
          const Object& this_ = static_cast<const Object&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Object::ByteSizeLong() const {
          const Object& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Object)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Object.ObjectType object_type = 1;
            if (this_._internal_object_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_object_type());
            }
          }
          switch (this_.literal_case()) {
            // int64 literal_int = 2;
            case kLiteralInt: {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_literal_int());
              break;
            }
            // double literal_float = 3;
            case kLiteralFloat: {
              total_size += 9;
              break;
            }
            // bool literal_bool = 4;
            case kLiteralBool: {
              total_size += 2;
              break;
            }
            // string literal_nil = 5;
            case kLiteralNil: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_literal_nil());
              break;
            }
            case LITERAL_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Object::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Object*>(&to_msg);
  auto& from = static_cast<const Object&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Object)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_object_type() != 0) {
    _this->_impl_.object_type_ = from._impl_.object_type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_literal();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLiteralInt: {
        _this->_impl_.literal_.literal_int_ = from._impl_.literal_.literal_int_;
        break;
      }
      case kLiteralFloat: {
        _this->_impl_.literal_.literal_float_ = from._impl_.literal_.literal_float_;
        break;
      }
      case kLiteralBool: {
        _this->_impl_.literal_.literal_bool_ = from._impl_.literal_.literal_bool_;
        break;
      }
      case kLiteralNil: {
        if (oneof_needs_init) {
          _this->_impl_.literal_.literal_nil_.InitDefault();
        }
        _this->_impl_.literal_.literal_nil_.Set(from._internal_literal_nil(), arena);
        break;
      }
      case LITERAL_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Object::CopyFrom(const Object& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Object)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Object::InternalSwap(Object* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.object_type_, other->_impl_.object_type_);
  swap(_impl_.literal_, other->_impl_.literal_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Object::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Chunk::_Internal {
 public:
};

Chunk::Chunk(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Chunk)
}
inline PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Chunk& from_msg)
      : constants_{visibility, arena, from.constants_},
        code_(arena, from.code_),
        _cached_size_{0} {}

Chunk::Chunk(
    ::google::protobuf::Arena* arena,
    const Chunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Chunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Object.Chunk)
}
inline PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : constants_{visibility, arena},
        code_(arena),
        _cached_size_{0} {}

inline void Chunk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Chunk::~Chunk() {
  // @@protoc_insertion_point(destructor:Object.Chunk)
  SharedDtor(*this);
}
inline void Chunk::SharedDtor(MessageLite& self) {
  Chunk& this_ = static_cast<Chunk&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Chunk::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Chunk(arena);
}
constexpr auto Chunk::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_) +
          decltype(Chunk::_impl_.constants_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Chunk), alignof(Chunk), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Chunk::PlacementNew_,
                                 sizeof(Chunk),
                                 alignof(Chunk));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Chunk::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Chunk_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Chunk::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Chunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Chunk::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Chunk>(), &Chunk::ByteSizeLong,
            &Chunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Chunk, _impl_._cached_size_),
        false,
    },
    &Chunk::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Chunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Chunk::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Chunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Object.Object constants = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_)}},
    // bytes code = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Chunk, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes code = 1;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated .Object.Object constants = 2;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Object::Object>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Chunk::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Chunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.constants_.Clear();
  _impl_.code_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Chunk::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Chunk::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Chunk)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes code = 1;
          if (!this_._internal_code().empty()) {
            const std::string& _s = this_._internal_code();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // repeated .Object.Object constants = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_constants_size());
               i < n; i++) {
            const auto& repfield = this_._internal_constants().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Chunk)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Chunk::ByteSizeLong(const MessageLite& base) {
          const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Chunk::ByteSizeLong() const {
          const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Chunk)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .Object.Object constants = 2;
            {
              total_size += 1UL * this_._internal_constants_size();
              for (const auto& msg : this_._internal_constants()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // bytes code = 1;
            if (!this_._internal_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Chunk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Chunk*>(&to_msg);
  auto& from = static_cast<const Chunk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Chunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_constants()->MergeFrom(
      from._internal_constants());
  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Chunk::CopyFrom(const Chunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Chunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Chunk::InternalSwap(Chunk* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.constants_.InternalSwap(&other->_impl_.constants_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_, &other->_impl_.code_, arena);
}

::google::protobuf::Metadata Chunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Object
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_object_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
