// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: object.proto
// Protobuf C++ Version: 5.29.5

#ifndef object_2eproto_2epb_2eh
#define object_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_object_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_object_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_object_2eproto;
namespace Object {
class Chunk;
struct ChunkDefaultTypeInternal;
extern ChunkDefaultTypeInternal _Chunk_default_instance_;
class Function;
struct FunctionDefaultTypeInternal;
extern FunctionDefaultTypeInternal _Function_default_instance_;
class Object;
struct ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
}  // namespace Object
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Object {
enum ObjectType : int {
  OBJ_INT = 0,
  OBJ_FLOAT = 1,
  OBJ_BOOL = 2,
  OBJ_NIL = 3,
  OBJ_STRING = 4,
  OBJ_FUNCTION = 5,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ObjectType_IsValid(int value);
extern const uint32_t ObjectType_internal_data_[];
constexpr ObjectType ObjectType_MIN = static_cast<ObjectType>(0);
constexpr ObjectType ObjectType_MAX = static_cast<ObjectType>(5);
constexpr int ObjectType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
ObjectType_descriptor();
template <typename T>
const std::string& ObjectType_Name(T value) {
  static_assert(std::is_same<T, ObjectType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ObjectType_Name().");
  return ObjectType_Name(static_cast<ObjectType>(value));
}
template <>
inline const std::string& ObjectType_Name(ObjectType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ObjectType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool ObjectType_Parse(absl::string_view name, ObjectType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectType>(
      ObjectType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Function final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Object.Function) */ {
 public:
  inline Function() : Function(nullptr) {}
  ~Function() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Function* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Function));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Function(
      ::google::protobuf::internal::ConstantInitialized);

  inline Function(const Function& from) : Function(nullptr, from) {}
  inline Function(Function&& from) noexcept
      : Function(nullptr, std::move(from)) {}
  inline Function& operator=(const Function& from) {
    CopyFrom(from);
    return *this;
  }
  inline Function& operator=(Function&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Function& default_instance() {
    return *internal_default_instance();
  }
  static inline const Function* internal_default_instance() {
    return reinterpret_cast<const Function*>(
        &_Function_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Function& a, Function& b) { a.Swap(&b); }
  inline void Swap(Function* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Function* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Function* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Function>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Function& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Function& from) { Function::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Function* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Object.Function"; }

 protected:
  explicit Function(::google::protobuf::Arena* arena);
  Function(::google::protobuf::Arena* arena, const Function& from);
  Function(::google::protobuf::Arena* arena, Function&& from) noexcept
      : Function(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCodeFieldNumber = 1,
    kNumParamsFieldNumber = 2,
  };
  // bytes code = 1;
  void clear_code() ;
  const std::string& code() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_code(Arg_&& arg, Args_... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* value);

  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(
      const std::string& value);
  std::string* _internal_mutable_code();

  public:
  // uint64 num_params = 2;
  void clear_num_params() ;
  ::uint64_t num_params() const;
  void set_num_params(::uint64_t value);

  private:
  ::uint64_t _internal_num_params() const;
  void _internal_set_num_params(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Object.Function)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Function& from_msg);
    ::google::protobuf::internal::ArenaStringPtr code_;
    ::uint64_t num_params_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_object_2eproto;
};
// -------------------------------------------------------------------

class Object final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Object.Object) */ {
 public:
  inline Object() : Object(nullptr) {}
  ~Object() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Object* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Object));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Object(
      ::google::protobuf::internal::ConstantInitialized);

  inline Object(const Object& from) : Object(nullptr, from) {}
  inline Object(Object&& from) noexcept
      : Object(nullptr, std::move(from)) {}
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  inline Object& operator=(Object&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Object& default_instance() {
    return *internal_default_instance();
  }
  enum LiteralCase {
    kLiteralInt = 3,
    kLiteralFloat = 4,
    kLiteralBool = 5,
    kLiteralNil = 6,
    kLiteralString = 7,
    kLiteralFunction = 8,
    LITERAL_NOT_SET = 0,
  };
  static inline const Object* internal_default_instance() {
    return reinterpret_cast<const Object*>(
        &_Object_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Object& a, Object& b) { a.Swap(&b); }
  inline void Swap(Object* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Object* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Object* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Object>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Object& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Object& from) { Object::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Object* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Object.Object"; }

 protected:
  explicit Object(::google::protobuf::Arena* arena);
  Object(::google::protobuf::Arena* arena, const Object& from);
  Object(::google::protobuf::Arena* arena, Object&& from) noexcept
      : Object(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRefCountFieldNumber = 2,
    kObjectTypeFieldNumber = 1,
    kLiteralIntFieldNumber = 3,
    kLiteralFloatFieldNumber = 4,
    kLiteralBoolFieldNumber = 5,
    kLiteralNilFieldNumber = 6,
    kLiteralStringFieldNumber = 7,
    kLiteralFunctionFieldNumber = 8,
  };
  // uint64 ref_count = 2;
  void clear_ref_count() ;
  ::uint64_t ref_count() const;
  void set_ref_count(::uint64_t value);

  private:
  ::uint64_t _internal_ref_count() const;
  void _internal_set_ref_count(::uint64_t value);

  public:
  // .Object.ObjectType object_type = 1;
  void clear_object_type() ;
  ::Object::ObjectType object_type() const;
  void set_object_type(::Object::ObjectType value);

  private:
  ::Object::ObjectType _internal_object_type() const;
  void _internal_set_object_type(::Object::ObjectType value);

  public:
  // int64 literal_int = 3;
  bool has_literal_int() const;
  void clear_literal_int() ;
  ::int64_t literal_int() const;
  void set_literal_int(::int64_t value);

  private:
  ::int64_t _internal_literal_int() const;
  void _internal_set_literal_int(::int64_t value);

  public:
  // double literal_float = 4;
  bool has_literal_float() const;
  void clear_literal_float() ;
  double literal_float() const;
  void set_literal_float(double value);

  private:
  double _internal_literal_float() const;
  void _internal_set_literal_float(double value);

  public:
  // bool literal_bool = 5;
  bool has_literal_bool() const;
  void clear_literal_bool() ;
  bool literal_bool() const;
  void set_literal_bool(bool value);

  private:
  bool _internal_literal_bool() const;
  void _internal_set_literal_bool(bool value);

  public:
  // string literal_nil = 6;
  bool has_literal_nil() const;
  void clear_literal_nil() ;
  const std::string& literal_nil() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_literal_nil(Arg_&& arg, Args_... args);
  std::string* mutable_literal_nil();
  PROTOBUF_NODISCARD std::string* release_literal_nil();
  void set_allocated_literal_nil(std::string* value);

  private:
  const std::string& _internal_literal_nil() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_literal_nil(
      const std::string& value);
  std::string* _internal_mutable_literal_nil();

  public:
  // string literal_string = 7;
  bool has_literal_string() const;
  void clear_literal_string() ;
  const std::string& literal_string() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_literal_string(Arg_&& arg, Args_... args);
  std::string* mutable_literal_string();
  PROTOBUF_NODISCARD std::string* release_literal_string();
  void set_allocated_literal_string(std::string* value);

  private:
  const std::string& _internal_literal_string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_literal_string(
      const std::string& value);
  std::string* _internal_mutable_literal_string();

  public:
  // .Object.Function literal_function = 8;
  bool has_literal_function() const;
  private:
  bool _internal_has_literal_function() const;

  public:
  void clear_literal_function() ;
  const ::Object::Function& literal_function() const;
  PROTOBUF_NODISCARD ::Object::Function* release_literal_function();
  ::Object::Function* mutable_literal_function();
  void set_allocated_literal_function(::Object::Function* value);
  void unsafe_arena_set_allocated_literal_function(::Object::Function* value);
  ::Object::Function* unsafe_arena_release_literal_function();

  private:
  const ::Object::Function& _internal_literal_function() const;
  ::Object::Function* _internal_mutable_literal_function();

  public:
  void clear_literal();
  LiteralCase literal_case() const;
  // @@protoc_insertion_point(class_scope:Object.Object)
 private:
  class _Internal;
  void set_has_literal_int();
  void set_has_literal_float();
  void set_has_literal_bool();
  void set_has_literal_nil();
  void set_has_literal_string();
  void set_has_literal_function();
  inline bool has_literal() const;
  inline void clear_has_literal();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 8, 1,
      55, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Object& from_msg);
    ::uint64_t ref_count_;
    int object_type_;
    union LiteralUnion {
      constexpr LiteralUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::int64_t literal_int_;
      double literal_float_;
      bool literal_bool_;
      ::google::protobuf::internal::ArenaStringPtr literal_nil_;
      ::google::protobuf::internal::ArenaStringPtr literal_string_;
      ::Object::Function* literal_function_;
    } literal_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_object_2eproto;
};
// -------------------------------------------------------------------

class Chunk final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Object.Chunk) */ {
 public:
  inline Chunk() : Chunk(nullptr) {}
  ~Chunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Chunk* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Chunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Chunk(
      ::google::protobuf::internal::ConstantInitialized);

  inline Chunk(const Chunk& from) : Chunk(nullptr, from) {}
  inline Chunk(Chunk&& from) noexcept
      : Chunk(nullptr, std::move(from)) {}
  inline Chunk& operator=(const Chunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chunk& operator=(Chunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chunk* internal_default_instance() {
    return reinterpret_cast<const Chunk*>(
        &_Chunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Chunk& a, Chunk& b) { a.Swap(&b); }
  inline void Swap(Chunk* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chunk* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Chunk* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Chunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Chunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Chunk& from) { Chunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Chunk* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Object.Chunk"; }

 protected:
  explicit Chunk(::google::protobuf::Arena* arena);
  Chunk(::google::protobuf::Arena* arena, const Chunk& from);
  Chunk(::google::protobuf::Arena* arena, Chunk&& from) noexcept
      : Chunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kConstantsFieldNumber = 2,
    kFunctionFieldNumber = 1,
    kGlobalsCountFieldNumber = 3,
  };
  // repeated .Object.Object constants = 2;
  int constants_size() const;
  private:
  int _internal_constants_size() const;

  public:
  void clear_constants() ;
  ::Object::Object* mutable_constants(int index);
  ::google::protobuf::RepeatedPtrField<::Object::Object>* mutable_constants();

  private:
  const ::google::protobuf::RepeatedPtrField<::Object::Object>& _internal_constants() const;
  ::google::protobuf::RepeatedPtrField<::Object::Object>* _internal_mutable_constants();
  public:
  const ::Object::Object& constants(int index) const;
  ::Object::Object* add_constants();
  const ::google::protobuf::RepeatedPtrField<::Object::Object>& constants() const;
  // .Object.Function function = 1;
  bool has_function() const;
  void clear_function() ;
  const ::Object::Function& function() const;
  PROTOBUF_NODISCARD ::Object::Function* release_function();
  ::Object::Function* mutable_function();
  void set_allocated_function(::Object::Function* value);
  void unsafe_arena_set_allocated_function(::Object::Function* value);
  ::Object::Function* unsafe_arena_release_function();

  private:
  const ::Object::Function& _internal_function() const;
  ::Object::Function* _internal_mutable_function();

  public:
  // uint64 globals_count = 3;
  void clear_globals_count() ;
  ::uint64_t globals_count() const;
  void set_globals_count(::uint64_t value);

  private:
  ::uint64_t _internal_globals_count() const;
  void _internal_set_globals_count(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Object.Chunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Chunk& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Object::Object > constants_;
    ::Object::Function* function_;
    ::uint64_t globals_count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_object_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Function

// bytes code = 1;
inline void Function::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.ClearToEmpty();
}
inline const std::string& Function::code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Function.code)
  return _internal_code();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Function::set_code(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Object.Function.code)
}
inline std::string* Function::mutable_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:Object.Function.code)
  return _s;
}
inline const std::string& Function::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_.Get();
}
inline void Function::_internal_set_code(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.Set(value, GetArena());
}
inline std::string* Function::_internal_mutable_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.code_.Mutable( GetArena());
}
inline std::string* Function::release_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Object.Function.code)
  return _impl_.code_.Release();
}
inline void Function::set_allocated_code(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Function.code)
}

// uint64 num_params = 2;
inline void Function::clear_num_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_params_ = ::uint64_t{0u};
}
inline ::uint64_t Function::num_params() const {
  // @@protoc_insertion_point(field_get:Object.Function.num_params)
  return _internal_num_params();
}
inline void Function::set_num_params(::uint64_t value) {
  _internal_set_num_params(value);
  // @@protoc_insertion_point(field_set:Object.Function.num_params)
}
inline ::uint64_t Function::_internal_num_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_params_;
}
inline void Function::_internal_set_num_params(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_params_ = value;
}

// -------------------------------------------------------------------

// Object

// .Object.ObjectType object_type = 1;
inline void Object::clear_object_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_type_ = 0;
}
inline ::Object::ObjectType Object::object_type() const {
  // @@protoc_insertion_point(field_get:Object.Object.object_type)
  return _internal_object_type();
}
inline void Object::set_object_type(::Object::ObjectType value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:Object.Object.object_type)
}
inline ::Object::ObjectType Object::_internal_object_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Object::ObjectType>(_impl_.object_type_);
}
inline void Object::_internal_set_object_type(::Object::ObjectType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_type_ = value;
}

// uint64 ref_count = 2;
inline void Object::clear_ref_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ref_count_ = ::uint64_t{0u};
}
inline ::uint64_t Object::ref_count() const {
  // @@protoc_insertion_point(field_get:Object.Object.ref_count)
  return _internal_ref_count();
}
inline void Object::set_ref_count(::uint64_t value) {
  _internal_set_ref_count(value);
  // @@protoc_insertion_point(field_set:Object.Object.ref_count)
}
inline ::uint64_t Object::_internal_ref_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ref_count_;
}
inline void Object::_internal_set_ref_count(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ref_count_ = value;
}

// int64 literal_int = 3;
inline bool Object::has_literal_int() const {
  return literal_case() == kLiteralInt;
}
inline void Object::set_has_literal_int() {
  _impl_._oneof_case_[0] = kLiteralInt;
}
inline void Object::clear_literal_int() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralInt) {
    _impl_.literal_.literal_int_ = ::int64_t{0};
    clear_has_literal();
  }
}
inline ::int64_t Object::literal_int() const {
  // @@protoc_insertion_point(field_get:Object.Object.literal_int)
  return _internal_literal_int();
}
inline void Object::set_literal_int(::int64_t value) {
  if (literal_case() != kLiteralInt) {
    clear_literal();
    set_has_literal_int();
  }
  _impl_.literal_.literal_int_ = value;
  // @@protoc_insertion_point(field_set:Object.Object.literal_int)
}
inline ::int64_t Object::_internal_literal_int() const {
  if (literal_case() == kLiteralInt) {
    return _impl_.literal_.literal_int_;
  }
  return ::int64_t{0};
}

// double literal_float = 4;
inline bool Object::has_literal_float() const {
  return literal_case() == kLiteralFloat;
}
inline void Object::set_has_literal_float() {
  _impl_._oneof_case_[0] = kLiteralFloat;
}
inline void Object::clear_literal_float() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralFloat) {
    _impl_.literal_.literal_float_ = 0;
    clear_has_literal();
  }
}
inline double Object::literal_float() const {
  // @@protoc_insertion_point(field_get:Object.Object.literal_float)
  return _internal_literal_float();
}
inline void Object::set_literal_float(double value) {
  if (literal_case() != kLiteralFloat) {
    clear_literal();
    set_has_literal_float();
  }
  _impl_.literal_.literal_float_ = value;
  // @@protoc_insertion_point(field_set:Object.Object.literal_float)
}
inline double Object::_internal_literal_float() const {
  if (literal_case() == kLiteralFloat) {
    return _impl_.literal_.literal_float_;
  }
  return 0;
}

// bool literal_bool = 5;
inline bool Object::has_literal_bool() const {
  return literal_case() == kLiteralBool;
}
inline void Object::set_has_literal_bool() {
  _impl_._oneof_case_[0] = kLiteralBool;
}
inline void Object::clear_literal_bool() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralBool) {
    _impl_.literal_.literal_bool_ = false;
    clear_has_literal();
  }
}
inline bool Object::literal_bool() const {
  // @@protoc_insertion_point(field_get:Object.Object.literal_bool)
  return _internal_literal_bool();
}
inline void Object::set_literal_bool(bool value) {
  if (literal_case() != kLiteralBool) {
    clear_literal();
    set_has_literal_bool();
  }
  _impl_.literal_.literal_bool_ = value;
  // @@protoc_insertion_point(field_set:Object.Object.literal_bool)
}
inline bool Object::_internal_literal_bool() const {
  if (literal_case() == kLiteralBool) {
    return _impl_.literal_.literal_bool_;
  }
  return false;
}

// string literal_nil = 6;
inline bool Object::has_literal_nil() const {
  return literal_case() == kLiteralNil;
}
inline void Object::set_has_literal_nil() {
  _impl_._oneof_case_[0] = kLiteralNil;
}
inline void Object::clear_literal_nil() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralNil) {
    _impl_.literal_.literal_nil_.Destroy();
    clear_has_literal();
  }
}
inline const std::string& Object::literal_nil() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Object.literal_nil)
  return _internal_literal_nil();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Object::set_literal_nil(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralNil) {
    clear_literal();

    set_has_literal_nil();
    _impl_.literal_.literal_nil_.InitDefault();
  }
  _impl_.literal_.literal_nil_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Object.Object.literal_nil)
}
inline std::string* Object::mutable_literal_nil() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_literal_nil();
  // @@protoc_insertion_point(field_mutable:Object.Object.literal_nil)
  return _s;
}
inline const std::string& Object::_internal_literal_nil() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (literal_case() != kLiteralNil) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.literal_.literal_nil_.Get();
}
inline void Object::_internal_set_literal_nil(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralNil) {
    clear_literal();

    set_has_literal_nil();
    _impl_.literal_.literal_nil_.InitDefault();
  }
  _impl_.literal_.literal_nil_.Set(value, GetArena());
}
inline std::string* Object::_internal_mutable_literal_nil() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralNil) {
    clear_literal();

    set_has_literal_nil();
    _impl_.literal_.literal_nil_.InitDefault();
  }
  return _impl_.literal_.literal_nil_.Mutable( GetArena());
}
inline std::string* Object::release_literal_nil() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Object.Object.literal_nil)
  if (literal_case() != kLiteralNil) {
    return nullptr;
  }
  clear_has_literal();
  return _impl_.literal_.literal_nil_.Release();
}
inline void Object::set_allocated_literal_nil(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_literal()) {
    clear_literal();
  }
  if (value != nullptr) {
    set_has_literal_nil();
    _impl_.literal_.literal_nil_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Object.literal_nil)
}

// string literal_string = 7;
inline bool Object::has_literal_string() const {
  return literal_case() == kLiteralString;
}
inline void Object::set_has_literal_string() {
  _impl_._oneof_case_[0] = kLiteralString;
}
inline void Object::clear_literal_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralString) {
    _impl_.literal_.literal_string_.Destroy();
    clear_has_literal();
  }
}
inline const std::string& Object::literal_string() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Object.literal_string)
  return _internal_literal_string();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Object::set_literal_string(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralString) {
    clear_literal();

    set_has_literal_string();
    _impl_.literal_.literal_string_.InitDefault();
  }
  _impl_.literal_.literal_string_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Object.Object.literal_string)
}
inline std::string* Object::mutable_literal_string() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_literal_string();
  // @@protoc_insertion_point(field_mutable:Object.Object.literal_string)
  return _s;
}
inline const std::string& Object::_internal_literal_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (literal_case() != kLiteralString) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.literal_.literal_string_.Get();
}
inline void Object::_internal_set_literal_string(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralString) {
    clear_literal();

    set_has_literal_string();
    _impl_.literal_.literal_string_.InitDefault();
  }
  _impl_.literal_.literal_string_.Set(value, GetArena());
}
inline std::string* Object::_internal_mutable_literal_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() != kLiteralString) {
    clear_literal();

    set_has_literal_string();
    _impl_.literal_.literal_string_.InitDefault();
  }
  return _impl_.literal_.literal_string_.Mutable( GetArena());
}
inline std::string* Object::release_literal_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Object.Object.literal_string)
  if (literal_case() != kLiteralString) {
    return nullptr;
  }
  clear_has_literal();
  return _impl_.literal_.literal_string_.Release();
}
inline void Object::set_allocated_literal_string(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_literal()) {
    clear_literal();
  }
  if (value != nullptr) {
    set_has_literal_string();
    _impl_.literal_.literal_string_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Object.literal_string)
}

// .Object.Function literal_function = 8;
inline bool Object::has_literal_function() const {
  return literal_case() == kLiteralFunction;
}
inline bool Object::_internal_has_literal_function() const {
  return literal_case() == kLiteralFunction;
}
inline void Object::set_has_literal_function() {
  _impl_._oneof_case_[0] = kLiteralFunction;
}
inline void Object::clear_literal_function() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (literal_case() == kLiteralFunction) {
    if (GetArena() == nullptr) {
      delete _impl_.literal_.literal_function_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.literal_.literal_function_);
    }
    clear_has_literal();
  }
}
inline ::Object::Function* Object::release_literal_function() {
  // @@protoc_insertion_point(field_release:Object.Object.literal_function)
  if (literal_case() == kLiteralFunction) {
    clear_has_literal();
    auto* temp = _impl_.literal_.literal_function_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.literal_.literal_function_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Object::Function& Object::_internal_literal_function() const {
  return literal_case() == kLiteralFunction ? *_impl_.literal_.literal_function_ : reinterpret_cast<::Object::Function&>(::Object::_Function_default_instance_);
}
inline const ::Object::Function& Object::literal_function() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Object.literal_function)
  return _internal_literal_function();
}
inline ::Object::Function* Object::unsafe_arena_release_literal_function() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Object.Object.literal_function)
  if (literal_case() == kLiteralFunction) {
    clear_has_literal();
    auto* temp = _impl_.literal_.literal_function_;
    _impl_.literal_.literal_function_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Object::unsafe_arena_set_allocated_literal_function(::Object::Function* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_literal();
  if (value) {
    set_has_literal_function();
    _impl_.literal_.literal_function_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Object.Object.literal_function)
}
inline ::Object::Function* Object::_internal_mutable_literal_function() {
  if (literal_case() != kLiteralFunction) {
    clear_literal();
    set_has_literal_function();
    _impl_.literal_.literal_function_ =
        ::google::protobuf::Message::DefaultConstruct<::Object::Function>(GetArena());
  }
  return _impl_.literal_.literal_function_;
}
inline ::Object::Function* Object::mutable_literal_function() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Object::Function* _msg = _internal_mutable_literal_function();
  // @@protoc_insertion_point(field_mutable:Object.Object.literal_function)
  return _msg;
}

inline bool Object::has_literal() const {
  return literal_case() != LITERAL_NOT_SET;
}
inline void Object::clear_has_literal() {
  _impl_._oneof_case_[0] = LITERAL_NOT_SET;
}
inline Object::LiteralCase Object::literal_case() const {
  return Object::LiteralCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Chunk

// .Object.Function function = 1;
inline bool Chunk::has_function() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.function_ != nullptr);
  return value;
}
inline void Chunk::clear_function() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.function_ != nullptr) _impl_.function_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Object::Function& Chunk::_internal_function() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Object::Function* p = _impl_.function_;
  return p != nullptr ? *p : reinterpret_cast<const ::Object::Function&>(::Object::_Function_default_instance_);
}
inline const ::Object::Function& Chunk::function() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Chunk.function)
  return _internal_function();
}
inline void Chunk::unsafe_arena_set_allocated_function(::Object::Function* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.function_);
  }
  _impl_.function_ = reinterpret_cast<::Object::Function*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Object.Chunk.function)
}
inline ::Object::Function* Chunk::release_function() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Object::Function* released = _impl_.function_;
  _impl_.function_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Object::Function* Chunk::unsafe_arena_release_function() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Object.Chunk.function)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Object::Function* temp = _impl_.function_;
  _impl_.function_ = nullptr;
  return temp;
}
inline ::Object::Function* Chunk::_internal_mutable_function() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.function_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Object::Function>(GetArena());
    _impl_.function_ = reinterpret_cast<::Object::Function*>(p);
  }
  return _impl_.function_;
}
inline ::Object::Function* Chunk::mutable_function() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Object::Function* _msg = _internal_mutable_function();
  // @@protoc_insertion_point(field_mutable:Object.Chunk.function)
  return _msg;
}
inline void Chunk::set_allocated_function(::Object::Function* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.function_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.function_ = reinterpret_cast<::Object::Function*>(value);
  // @@protoc_insertion_point(field_set_allocated:Object.Chunk.function)
}

// repeated .Object.Object constants = 2;
inline int Chunk::_internal_constants_size() const {
  return _internal_constants().size();
}
inline int Chunk::constants_size() const {
  return _internal_constants_size();
}
inline void Chunk::clear_constants() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.constants_.Clear();
}
inline ::Object::Object* Chunk::mutable_constants(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Object.Chunk.constants)
  return _internal_mutable_constants()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Object::Object>* Chunk::mutable_constants()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Object.Chunk.constants)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_constants();
}
inline const ::Object::Object& Chunk::constants(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Object.Chunk.constants)
  return _internal_constants().Get(index);
}
inline ::Object::Object* Chunk::add_constants() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Object::Object* _add = _internal_mutable_constants()->Add();
  // @@protoc_insertion_point(field_add:Object.Chunk.constants)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Object::Object>& Chunk::constants() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Object.Chunk.constants)
  return _internal_constants();
}
inline const ::google::protobuf::RepeatedPtrField<::Object::Object>&
Chunk::_internal_constants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.constants_;
}
inline ::google::protobuf::RepeatedPtrField<::Object::Object>*
Chunk::_internal_mutable_constants() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.constants_;
}

// uint64 globals_count = 3;
inline void Chunk::clear_globals_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.globals_count_ = ::uint64_t{0u};
}
inline ::uint64_t Chunk::globals_count() const {
  // @@protoc_insertion_point(field_get:Object.Chunk.globals_count)
  return _internal_globals_count();
}
inline void Chunk::set_globals_count(::uint64_t value) {
  _internal_set_globals_count(value);
  // @@protoc_insertion_point(field_set:Object.Chunk.globals_count)
}
inline ::uint64_t Chunk::_internal_globals_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.globals_count_;
}
inline void Chunk::_internal_set_globals_count(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.globals_count_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Object


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Object::ObjectType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Object::ObjectType>() {
  return ::Object::ObjectType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // object_2eproto_2epb_2eh
