// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: object.proto
// Protobuf C++ Version: 5.29.5

#include "object.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Object {

inline constexpr Function::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        num_params_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Function::Function(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FunctionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FunctionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FunctionDefaultTypeInternal() {}
  union {
    Function _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FunctionDefaultTypeInternal _Function_default_instance_;

inline constexpr Closure::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        function_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Closure::Closure(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClosureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClosureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClosureDefaultTypeInternal() {}
  union {
    Closure _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClosureDefaultTypeInternal _Closure_default_instance_;

inline constexpr Object::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ref_count_{::uint64_t{0u}},
        object_type_{static_cast< ::Object::ObjectType >(0)},
        literal_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Object::Object(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObjectDefaultTypeInternal() {}
  union {
    Object _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObjectDefaultTypeInternal _Object_default_instance_;

inline constexpr Chunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        constants_{},
        function_{nullptr},
        globals_count_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR Chunk::Chunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChunkDefaultTypeInternal() {}
  union {
    Chunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChunkDefaultTypeInternal _Chunk_default_instance_;
}  // namespace Object
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_object_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_object_2eproto = nullptr;
const ::uint32_t
    TableStruct_object_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Object::Function, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Function, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::Object::Function, _impl_.num_params_),
        PROTOBUF_FIELD_OFFSET(::Object::Closure, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Object::Closure, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Closure, _impl_.function_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Object::Object, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_.object_type_),
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_.ref_count_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_.literal_),
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_.function_),
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_.constants_),
        PROTOBUF_FIELD_OFFSET(::Object::Chunk, _impl_.globals_count_),
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Object::Function)},
        {10, 19, -1, sizeof(::Object::Closure)},
        {20, -1, -1, sizeof(::Object::Object)},
        {38, 49, -1, sizeof(::Object::Chunk)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Object::_Function_default_instance_._instance,
    &::Object::_Closure_default_instance_._instance,
    &::Object::_Object_default_instance_._instance,
    &::Object::_Chunk_default_instance_._instance,
};
const char descriptor_table_protodef_object_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014object.proto\022\006Object\",\n\010Function\022\014\n\004co"
    "de\030\001 \001(\014\022\022\n\nnum_params\030\002 \001(\004\"-\n\007Closure\022"
    "\"\n\010function\030\001 \001(\0132\020.Object.Function\"\242\002\n\006"
    "Object\022\'\n\013object_type\030\001 \001(\0162\022.Object.Obj"
    "ectType\022\021\n\tref_count\030\002 \001(\004\022\025\n\013literal_in"
    "t\030\003 \001(\003H\000\022\027\n\rliteral_float\030\004 \001(\001H\000\022\026\n\014li"
    "teral_bool\030\005 \001(\010H\000\022\025\n\013literal_nil\030\006 \001(\tH"
    "\000\022\030\n\016literal_string\030\007 \001(\tH\000\022,\n\020literal_f"
    "unction\030\010 \001(\0132\020.Object.FunctionH\000\022*\n\017lit"
    "eral_closure\030\t \001(\0132\017.Object.ClosureH\000B\t\n"
    "\007literal\"e\n\005Chunk\022\"\n\010function\030\001 \001(\0132\020.Ob"
    "ject.Function\022!\n\tconstants\030\002 \003(\0132\016.Objec"
    "t.Object\022\025\n\rglobals_count\030\003 \001(\004*v\n\nObjec"
    "tType\022\013\n\007OBJ_INT\020\000\022\r\n\tOBJ_FLOAT\020\001\022\014\n\010OBJ"
    "_BOOL\020\002\022\013\n\007OBJ_NIL\020\003\022\016\n\nOBJ_STRING\020\004\022\020\n\014"
    "OBJ_FUNCTION\020\005\022\017\n\013OBJ_CLOSURE\020\006B\004Z\002./b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_object_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_object_2eproto = {
    false,
    false,
    645,
    descriptor_table_protodef_object_2eproto,
    "object.proto",
    &descriptor_table_object_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_object_2eproto::offsets,
    file_level_enum_descriptors_object_2eproto,
    file_level_service_descriptors_object_2eproto,
};
namespace Object {
const ::google::protobuf::EnumDescriptor* ObjectType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_object_2eproto);
  return file_level_enum_descriptors_object_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ObjectType_internal_data_[] = {
    458752u, 0u, };
bool ObjectType_IsValid(int value) {
  return 0 <= value && value <= 6;
}
// ===================================================================

class Function::_Internal {
 public:
};

Function::Function(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Function)
}
inline PROTOBUF_NDEBUG_INLINE Function::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Function& from_msg)
      : code_(arena, from.code_),
        _cached_size_{0} {}

Function::Function(
    ::google::protobuf::Arena* arena,
    const Function& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Function* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.num_params_ = from._impl_.num_params_;

  // @@protoc_insertion_point(copy_constructor:Object.Function)
}
inline PROTOBUF_NDEBUG_INLINE Function::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : code_(arena),
        _cached_size_{0} {}

inline void Function::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.num_params_ = {};
}
Function::~Function() {
  // @@protoc_insertion_point(destructor:Object.Function)
  SharedDtor(*this);
}
inline void Function::SharedDtor(MessageLite& self) {
  Function& this_ = static_cast<Function&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Function::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Function(arena);
}
constexpr auto Function::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Function),
                                            alignof(Function));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Function::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Function_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Function::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Function>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Function::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Function>(), &Function::ByteSizeLong,
            &Function::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Function, _impl_._cached_size_),
        false,
    },
    &Function::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Function::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Function::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Function>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 num_params = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Function, _impl_.num_params_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Function, _impl_.num_params_)}},
    // bytes code = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Function, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes code = 1;
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 num_params = 2;
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.num_params_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Function::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Function)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.ClearToEmpty();
  _impl_.num_params_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Function::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Function& this_ = static_cast<const Function&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Function::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Function& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Function)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes code = 1;
          if (!this_._internal_code().empty()) {
            const std::string& _s = this_._internal_code();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // uint64 num_params = 2;
          if (this_._internal_num_params() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_num_params(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Function)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Function::ByteSizeLong(const MessageLite& base) {
          const Function& this_ = static_cast<const Function&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Function::ByteSizeLong() const {
          const Function& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Function)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes code = 1;
            if (!this_._internal_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_code());
            }
            // uint64 num_params = 2;
            if (this_._internal_num_params() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_num_params());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Function::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Function*>(&to_msg);
  auto& from = static_cast<const Function&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Function)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (from._internal_num_params() != 0) {
    _this->_impl_.num_params_ = from._impl_.num_params_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Function::CopyFrom(const Function& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Function)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Function::InternalSwap(Function* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_, &other->_impl_.code_, arena);
        swap(_impl_.num_params_, other->_impl_.num_params_);
}

::google::protobuf::Metadata Function::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Closure::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Closure>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Closure, _impl_._has_bits_);
};

Closure::Closure(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Closure)
}
inline PROTOBUF_NDEBUG_INLINE Closure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Closure& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Closure::Closure(
    ::google::protobuf::Arena* arena,
    const Closure& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Closure* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.function_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Object::Function>(
                              arena, *from._impl_.function_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Object.Closure)
}
inline PROTOBUF_NDEBUG_INLINE Closure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Closure::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.function_ = {};
}
Closure::~Closure() {
  // @@protoc_insertion_point(destructor:Object.Closure)
  SharedDtor(*this);
}
inline void Closure::SharedDtor(MessageLite& self) {
  Closure& this_ = static_cast<Closure&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.function_;
  this_._impl_.~Impl_();
}

inline void* Closure::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Closure(arena);
}
constexpr auto Closure::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Closure),
                                            alignof(Closure));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Closure::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Closure_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Closure::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Closure>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Closure::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Closure>(), &Closure::ByteSizeLong,
            &Closure::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Closure, _impl_._cached_size_),
        false,
    },
    &Closure::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Closure::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Closure::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Closure, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Closure>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Object.Function function = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Closure, _impl_.function_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Object.Function function = 1;
    {PROTOBUF_FIELD_OFFSET(Closure, _impl_.function_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Object::Function>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Closure::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Closure)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.function_ != nullptr);
    _impl_.function_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Closure::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Closure& this_ = static_cast<const Closure&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Closure::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Closure& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Closure)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Object.Function function = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.function_, this_._impl_.function_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Closure)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Closure::ByteSizeLong(const MessageLite& base) {
          const Closure& this_ = static_cast<const Closure&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Closure::ByteSizeLong() const {
          const Closure& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Closure)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Object.Function function = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.function_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Closure::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Closure*>(&to_msg);
  auto& from = static_cast<const Closure&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Closure)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.function_ != nullptr);
    if (_this->_impl_.function_ == nullptr) {
      _this->_impl_.function_ =
          ::google::protobuf::Message::CopyConstruct<::Object::Function>(arena, *from._impl_.function_);
    } else {
      _this->_impl_.function_->MergeFrom(*from._impl_.function_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Closure::CopyFrom(const Closure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Closure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Closure::InternalSwap(Closure* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.function_, other->_impl_.function_);
}

::google::protobuf::Metadata Closure::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Object::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Object::Object, _impl_._oneof_case_);
};

void Object::set_allocated_literal_function(::Object::Function* literal_function) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_literal();
  if (literal_function) {
    ::google::protobuf::Arena* submessage_arena = literal_function->GetArena();
    if (message_arena != submessage_arena) {
      literal_function = ::google::protobuf::internal::GetOwnedMessage(message_arena, literal_function, submessage_arena);
    }
    set_has_literal_function();
    _impl_.literal_.literal_function_ = literal_function;
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Object.literal_function)
}
void Object::set_allocated_literal_closure(::Object::Closure* literal_closure) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_literal();
  if (literal_closure) {
    ::google::protobuf::Arena* submessage_arena = literal_closure->GetArena();
    if (message_arena != submessage_arena) {
      literal_closure = ::google::protobuf::internal::GetOwnedMessage(message_arena, literal_closure, submessage_arena);
    }
    set_has_literal_closure();
    _impl_.literal_.literal_closure_ = literal_closure;
  }
  // @@protoc_insertion_point(field_set_allocated:Object.Object.literal_closure)
}
Object::Object(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Object)
}
inline PROTOBUF_NDEBUG_INLINE Object::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Object& from_msg)
      : literal_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Object::Object(
    ::google::protobuf::Arena* arena,
    const Object& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Object* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ref_count_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ref_count_),
           offsetof(Impl_, object_type_) -
               offsetof(Impl_, ref_count_) +
               sizeof(Impl_::object_type_));
  switch (literal_case()) {
    case LITERAL_NOT_SET:
      break;
      case kLiteralInt:
        _impl_.literal_.literal_int_ = from._impl_.literal_.literal_int_;
        break;
      case kLiteralFloat:
        _impl_.literal_.literal_float_ = from._impl_.literal_.literal_float_;
        break;
      case kLiteralBool:
        _impl_.literal_.literal_bool_ = from._impl_.literal_.literal_bool_;
        break;
      case kLiteralNil:
        new (&_impl_.literal_.literal_nil_) decltype(_impl_.literal_.literal_nil_){arena, from._impl_.literal_.literal_nil_};
        break;
      case kLiteralString:
        new (&_impl_.literal_.literal_string_) decltype(_impl_.literal_.literal_string_){arena, from._impl_.literal_.literal_string_};
        break;
      case kLiteralFunction:
        _impl_.literal_.literal_function_ = ::google::protobuf::Message::CopyConstruct<::Object::Function>(arena, *from._impl_.literal_.literal_function_);
        break;
      case kLiteralClosure:
        _impl_.literal_.literal_closure_ = ::google::protobuf::Message::CopyConstruct<::Object::Closure>(arena, *from._impl_.literal_.literal_closure_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Object.Object)
}
inline PROTOBUF_NDEBUG_INLINE Object::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : literal_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Object::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ref_count_),
           0,
           offsetof(Impl_, object_type_) -
               offsetof(Impl_, ref_count_) +
               sizeof(Impl_::object_type_));
}
Object::~Object() {
  // @@protoc_insertion_point(destructor:Object.Object)
  SharedDtor(*this);
}
inline void Object::SharedDtor(MessageLite& self) {
  Object& this_ = static_cast<Object&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_literal()) {
    this_.clear_literal();
  }
  this_._impl_.~Impl_();
}

void Object::clear_literal() {
// @@protoc_insertion_point(one_of_clear_start:Object.Object)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (literal_case()) {
    case kLiteralInt: {
      // No need to clear
      break;
    }
    case kLiteralFloat: {
      // No need to clear
      break;
    }
    case kLiteralBool: {
      // No need to clear
      break;
    }
    case kLiteralNil: {
      _impl_.literal_.literal_nil_.Destroy();
      break;
    }
    case kLiteralString: {
      _impl_.literal_.literal_string_.Destroy();
      break;
    }
    case kLiteralFunction: {
      if (GetArena() == nullptr) {
        delete _impl_.literal_.literal_function_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.literal_.literal_function_);
      }
      break;
    }
    case kLiteralClosure: {
      if (GetArena() == nullptr) {
        delete _impl_.literal_.literal_closure_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.literal_.literal_closure_);
      }
      break;
    }
    case LITERAL_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = LITERAL_NOT_SET;
}


inline void* Object::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Object(arena);
}
constexpr auto Object::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Object),
                                            alignof(Object));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Object::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Object_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Object::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Object>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Object::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Object>(), &Object::ByteSizeLong,
            &Object::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Object, _impl_._cached_size_),
        false,
    },
    &Object::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Object::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 9, 2, 55, 2> Object::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Object>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 ref_count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Object, _impl_.ref_count_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Object, _impl_.ref_count_)}},
    // .Object.ObjectType object_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Object, _impl_.object_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Object, _impl_.object_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Object.ObjectType object_type = 1;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.object_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint64 ref_count = 2;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.ref_count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // int64 literal_int = 3;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_int_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // double literal_float = 4;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_float_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // bool literal_bool = 5;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_bool_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // string literal_nil = 6;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_nil_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string literal_string = 7;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_string_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Object.Function literal_function = 8;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_function_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Object.Closure literal_closure = 9;
    {PROTOBUF_FIELD_OFFSET(Object, _impl_.literal_.literal_closure_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Object::Function>()},
    {::_pbi::TcParser::GetTable<::Object::Closure>()},
  }}, {{
    "\15\0\0\0\0\0\13\16\0\0\0\0\0\0\0\0"
    "Object.Object"
    "literal_nil"
    "literal_string"
  }},
};

PROTOBUF_NOINLINE void Object::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Object)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ref_count_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.object_type_) -
      reinterpret_cast<char*>(&_impl_.ref_count_)) + sizeof(_impl_.object_type_));
  clear_literal();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Object::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Object& this_ = static_cast<const Object&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Object::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Object& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Object)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .Object.ObjectType object_type = 1;
          if (this_._internal_object_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_object_type(), target);
          }

          // uint64 ref_count = 2;
          if (this_._internal_ref_count() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_ref_count(), target);
          }

          switch (this_.literal_case()) {
            case kLiteralInt: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt64ToArrayWithField<3>(
                      stream, this_._internal_literal_int(), target);
              break;
            }
            case kLiteralFloat: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                  4, this_._internal_literal_float(), target);
              break;
            }
            case kLiteralBool: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteBoolToArray(
                  5, this_._internal_literal_bool(), target);
              break;
            }
            case kLiteralNil: {
              const std::string& _s = this_._internal_literal_nil();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Object.Object.literal_nil");
              target = stream->WriteStringMaybeAliased(6, _s, target);
              break;
            }
            case kLiteralString: {
              const std::string& _s = this_._internal_literal_string();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Object.Object.literal_string");
              target = stream->WriteStringMaybeAliased(7, _s, target);
              break;
            }
            case kLiteralFunction: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  8, *this_._impl_.literal_.literal_function_, this_._impl_.literal_.literal_function_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kLiteralClosure: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  9, *this_._impl_.literal_.literal_closure_, this_._impl_.literal_.literal_closure_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Object)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Object::ByteSizeLong(const MessageLite& base) {
          const Object& this_ = static_cast<const Object&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Object::ByteSizeLong() const {
          const Object& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Object)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 ref_count = 2;
            if (this_._internal_ref_count() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_ref_count());
            }
            // .Object.ObjectType object_type = 1;
            if (this_._internal_object_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_object_type());
            }
          }
          switch (this_.literal_case()) {
            // int64 literal_int = 3;
            case kLiteralInt: {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_literal_int());
              break;
            }
            // double literal_float = 4;
            case kLiteralFloat: {
              total_size += 9;
              break;
            }
            // bool literal_bool = 5;
            case kLiteralBool: {
              total_size += 2;
              break;
            }
            // string literal_nil = 6;
            case kLiteralNil: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_literal_nil());
              break;
            }
            // string literal_string = 7;
            case kLiteralString: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_literal_string());
              break;
            }
            // .Object.Function literal_function = 8;
            case kLiteralFunction: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.literal_.literal_function_);
              break;
            }
            // .Object.Closure literal_closure = 9;
            case kLiteralClosure: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.literal_.literal_closure_);
              break;
            }
            case LITERAL_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Object::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Object*>(&to_msg);
  auto& from = static_cast<const Object&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Object)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ref_count() != 0) {
    _this->_impl_.ref_count_ = from._impl_.ref_count_;
  }
  if (from._internal_object_type() != 0) {
    _this->_impl_.object_type_ = from._impl_.object_type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_literal();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLiteralInt: {
        _this->_impl_.literal_.literal_int_ = from._impl_.literal_.literal_int_;
        break;
      }
      case kLiteralFloat: {
        _this->_impl_.literal_.literal_float_ = from._impl_.literal_.literal_float_;
        break;
      }
      case kLiteralBool: {
        _this->_impl_.literal_.literal_bool_ = from._impl_.literal_.literal_bool_;
        break;
      }
      case kLiteralNil: {
        if (oneof_needs_init) {
          _this->_impl_.literal_.literal_nil_.InitDefault();
        }
        _this->_impl_.literal_.literal_nil_.Set(from._internal_literal_nil(), arena);
        break;
      }
      case kLiteralString: {
        if (oneof_needs_init) {
          _this->_impl_.literal_.literal_string_.InitDefault();
        }
        _this->_impl_.literal_.literal_string_.Set(from._internal_literal_string(), arena);
        break;
      }
      case kLiteralFunction: {
        if (oneof_needs_init) {
          _this->_impl_.literal_.literal_function_ =
              ::google::protobuf::Message::CopyConstruct<::Object::Function>(arena, *from._impl_.literal_.literal_function_);
        } else {
          _this->_impl_.literal_.literal_function_->MergeFrom(from._internal_literal_function());
        }
        break;
      }
      case kLiteralClosure: {
        if (oneof_needs_init) {
          _this->_impl_.literal_.literal_closure_ =
              ::google::protobuf::Message::CopyConstruct<::Object::Closure>(arena, *from._impl_.literal_.literal_closure_);
        } else {
          _this->_impl_.literal_.literal_closure_->MergeFrom(from._internal_literal_closure());
        }
        break;
      }
      case LITERAL_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Object::CopyFrom(const Object& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Object)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Object::InternalSwap(Object* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Object, _impl_.object_type_)
      + sizeof(Object::_impl_.object_type_)
      - PROTOBUF_FIELD_OFFSET(Object, _impl_.ref_count_)>(
          reinterpret_cast<char*>(&_impl_.ref_count_),
          reinterpret_cast<char*>(&other->_impl_.ref_count_));
  swap(_impl_.literal_, other->_impl_.literal_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Object::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Chunk::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Chunk>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Chunk, _impl_._has_bits_);
};

Chunk::Chunk(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Object.Chunk)
}
inline PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Object::Chunk& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        constants_{visibility, arena, from.constants_} {}

Chunk::Chunk(
    ::google::protobuf::Arena* arena,
    const Chunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Chunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.function_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Object::Function>(
                              arena, *from._impl_.function_)
                        : nullptr;
  _impl_.globals_count_ = from._impl_.globals_count_;

  // @@protoc_insertion_point(copy_constructor:Object.Chunk)
}
inline PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        constants_{visibility, arena} {}

inline void Chunk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, function_),
           0,
           offsetof(Impl_, globals_count_) -
               offsetof(Impl_, function_) +
               sizeof(Impl_::globals_count_));
}
Chunk::~Chunk() {
  // @@protoc_insertion_point(destructor:Object.Chunk)
  SharedDtor(*this);
}
inline void Chunk::SharedDtor(MessageLite& self) {
  Chunk& this_ = static_cast<Chunk&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.function_;
  this_._impl_.~Impl_();
}

inline void* Chunk::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Chunk(arena);
}
constexpr auto Chunk::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_) +
          decltype(Chunk::_impl_.constants_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Chunk), alignof(Chunk), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Chunk::PlacementNew_,
                                 sizeof(Chunk),
                                 alignof(Chunk));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Chunk::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Chunk_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Chunk::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Chunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Chunk::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Chunk>(), &Chunk::ByteSizeLong,
            &Chunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Chunk, _impl_._cached_size_),
        false,
    },
    &Chunk::kDescriptorMethods,
    &descriptor_table_object_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Chunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> Chunk::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Chunk, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Object::Chunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .Object.Function function = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Chunk, _impl_.function_)}},
    // repeated .Object.Object constants = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_)}},
    // uint64 globals_count = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Chunk, _impl_.globals_count_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Chunk, _impl_.globals_count_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Object.Function function = 1;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.function_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .Object.Object constants = 2;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.constants_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint64 globals_count = 3;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.globals_count_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Object::Function>()},
    {::_pbi::TcParser::GetTable<::Object::Object>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Chunk::Clear() {
// @@protoc_insertion_point(message_clear_start:Object.Chunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.constants_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.function_ != nullptr);
    _impl_.function_->Clear();
  }
  _impl_.globals_count_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Chunk::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Chunk::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Object.Chunk)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Object.Function function = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.function_, this_._impl_.function_->GetCachedSize(), target,
                stream);
          }

          // repeated .Object.Object constants = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_constants_size());
               i < n; i++) {
            const auto& repfield = this_._internal_constants().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // uint64 globals_count = 3;
          if (this_._internal_globals_count() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                3, this_._internal_globals_count(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Object.Chunk)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Chunk::ByteSizeLong(const MessageLite& base) {
          const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Chunk::ByteSizeLong() const {
          const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Object.Chunk)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .Object.Object constants = 2;
            {
              total_size += 1UL * this_._internal_constants_size();
              for (const auto& msg : this_._internal_constants()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // .Object.Function function = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.function_);
            }
          }
           {
            // uint64 globals_count = 3;
            if (this_._internal_globals_count() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_globals_count());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Chunk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Chunk*>(&to_msg);
  auto& from = static_cast<const Chunk&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Object.Chunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_constants()->MergeFrom(
      from._internal_constants());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.function_ != nullptr);
    if (_this->_impl_.function_ == nullptr) {
      _this->_impl_.function_ =
          ::google::protobuf::Message::CopyConstruct<::Object::Function>(arena, *from._impl_.function_);
    } else {
      _this->_impl_.function_->MergeFrom(*from._impl_.function_);
    }
  }
  if (from._internal_globals_count() != 0) {
    _this->_impl_.globals_count_ = from._impl_.globals_count_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Chunk::CopyFrom(const Chunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Object.Chunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Chunk::InternalSwap(Chunk* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.constants_.InternalSwap(&other->_impl_.constants_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.globals_count_)
      + sizeof(Chunk::_impl_.globals_count_)
      - PROTOBUF_FIELD_OFFSET(Chunk, _impl_.function_)>(
          reinterpret_cast<char*>(&_impl_.function_),
          reinterpret_cast<char*>(&other->_impl_.function_));
}

::google::protobuf::Metadata Chunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Object
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_object_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
