// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: object.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJ_INT      ObjectType = 0
	ObjectType_OBJ_FLOAT    ObjectType = 1
	ObjectType_OBJ_BOOL     ObjectType = 2
	ObjectType_OBJ_NIL      ObjectType = 3
	ObjectType_OBJ_STRING   ObjectType = 4
	ObjectType_OBJ_FUNCTION ObjectType = 5
	ObjectType_OBJ_CLOSURE  ObjectType = 6
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJ_INT",
		1: "OBJ_FLOAT",
		2: "OBJ_BOOL",
		3: "OBJ_NIL",
		4: "OBJ_STRING",
		5: "OBJ_FUNCTION",
		6: "OBJ_CLOSURE",
	}
	ObjectType_value = map[string]int32{
		"OBJ_INT":      0,
		"OBJ_FLOAT":    1,
		"OBJ_BOOL":     2,
		"OBJ_NIL":      3,
		"OBJ_STRING":   4,
		"OBJ_FUNCTION": 5,
		"OBJ_CLOSURE":  6,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_object_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_object_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	NumParams     uint64                 `protobuf:"varint,2,opt,name=num_params,json=numParams,proto3" json:"num_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Function) GetNumParams() uint64 {
	if x != nil {
		return x.NumParams
	}
	return 0
}

type Closure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Closure) Reset() {
	*x = Closure{}
	mi := &file_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Closure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Closure) ProtoMessage() {}

func (x *Closure) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Closure.ProtoReflect.Descriptor instead.
func (*Closure) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{1}
}

func (x *Closure) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type Object struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ObjectType ObjectType             `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=Object.ObjectType" json:"object_type,omitempty"`
	RefCount   uint64                 `protobuf:"varint,2,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	// Types that are valid to be assigned to Literal:
	//
	//	*Object_LiteralInt
	//	*Object_LiteralFloat
	//	*Object_LiteralBool
	//	*Object_LiteralNil
	//	*Object_LiteralString
	//	*Object_LiteralFunction
	//	*Object_LiteralClosure
	Literal       isObject_Literal `protobuf_oneof:"literal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJ_INT
}

func (x *Object) GetRefCount() uint64 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *Object) GetLiteral() isObject_Literal {
	if x != nil {
		return x.Literal
	}
	return nil
}

func (x *Object) GetLiteralInt() int64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralInt); ok {
			return x.LiteralInt
		}
	}
	return 0
}

func (x *Object) GetLiteralFloat() float64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralFloat); ok {
			return x.LiteralFloat
		}
	}
	return 0
}

func (x *Object) GetLiteralBool() bool {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralBool); ok {
			return x.LiteralBool
		}
	}
	return false
}

func (x *Object) GetLiteralNil() string {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralNil); ok {
			return x.LiteralNil
		}
	}
	return ""
}

func (x *Object) GetLiteralString() string {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralString); ok {
			return x.LiteralString
		}
	}
	return ""
}

func (x *Object) GetLiteralFunction() *Function {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralFunction); ok {
			return x.LiteralFunction
		}
	}
	return nil
}

func (x *Object) GetLiteralClosure() *Closure {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralClosure); ok {
			return x.LiteralClosure
		}
	}
	return nil
}

type isObject_Literal interface {
	isObject_Literal()
}

type Object_LiteralInt struct {
	LiteralInt int64 `protobuf:"varint,3,opt,name=literal_int,json=literalInt,proto3,oneof"`
}

type Object_LiteralFloat struct {
	LiteralFloat float64 `protobuf:"fixed64,4,opt,name=literal_float,json=literalFloat,proto3,oneof"`
}

type Object_LiteralBool struct {
	LiteralBool bool `protobuf:"varint,5,opt,name=literal_bool,json=literalBool,proto3,oneof"`
}

type Object_LiteralNil struct {
	LiteralNil string `protobuf:"bytes,6,opt,name=literal_nil,json=literalNil,proto3,oneof"`
}

type Object_LiteralString struct {
	LiteralString string `protobuf:"bytes,7,opt,name=literal_string,json=literalString,proto3,oneof"`
}

type Object_LiteralFunction struct {
	LiteralFunction *Function `protobuf:"bytes,8,opt,name=literal_function,json=literalFunction,proto3,oneof"`
}

type Object_LiteralClosure struct {
	LiteralClosure *Closure `protobuf:"bytes,9,opt,name=literal_closure,json=literalClosure,proto3,oneof"`
}

func (*Object_LiteralInt) isObject_Literal() {}

func (*Object_LiteralFloat) isObject_Literal() {}

func (*Object_LiteralBool) isObject_Literal() {}

func (*Object_LiteralNil) isObject_Literal() {}

func (*Object_LiteralString) isObject_Literal() {}

func (*Object_LiteralFunction) isObject_Literal() {}

func (*Object_LiteralClosure) isObject_Literal() {}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Constants     []*Object              `protobuf:"bytes,2,rep,name=constants,proto3" json:"constants,omitempty"`
	GlobalsCount  uint64                 `protobuf:"varint,3,opt,name=globals_count,json=globalsCount,proto3" json:"globals_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Chunk) GetConstants() []*Object {
	if x != nil {
		return x.Constants
	}
	return nil
}

func (x *Chunk) GetGlobalsCount() uint64 {
	if x != nil {
		return x.GlobalsCount
	}
	return 0
}

var File_object_proto protoreflect.FileDescriptor

const file_object_proto_rawDesc = "" +
	"\n" +
	"\fobject.proto\x12\x06Object\"=\n" +
	"\bFunction\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04code\x12\x1d\n" +
	"\n" +
	"num_params\x18\x02 \x01(\x04R\tnumParams\"7\n" +
	"\aClosure\x12,\n" +
	"\bfunction\x18\x01 \x01(\v2\x10.Object.FunctionR\bfunction\"\x9b\x03\n" +
	"\x06Object\x123\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x12.Object.ObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tref_count\x18\x02 \x01(\x04R\brefCount\x12!\n" +
	"\vliteral_int\x18\x03 \x01(\x03H\x00R\n" +
	"literalInt\x12%\n" +
	"\rliteral_float\x18\x04 \x01(\x01H\x00R\fliteralFloat\x12#\n" +
	"\fliteral_bool\x18\x05 \x01(\bH\x00R\vliteralBool\x12!\n" +
	"\vliteral_nil\x18\x06 \x01(\tH\x00R\n" +
	"literalNil\x12'\n" +
	"\x0eliteral_string\x18\a \x01(\tH\x00R\rliteralString\x12=\n" +
	"\x10literal_function\x18\b \x01(\v2\x10.Object.FunctionH\x00R\x0fliteralFunction\x12:\n" +
	"\x0fliteral_closure\x18\t \x01(\v2\x0f.Object.ClosureH\x00R\x0eliteralClosureB\t\n" +
	"\aliteral\"\x88\x01\n" +
	"\x05Chunk\x12,\n" +
	"\bfunction\x18\x01 \x01(\v2\x10.Object.FunctionR\bfunction\x12,\n" +
	"\tconstants\x18\x02 \x03(\v2\x0e.Object.ObjectR\tconstants\x12#\n" +
	"\rglobals_count\x18\x03 \x01(\x04R\fglobalsCount*v\n" +
	"\n" +
	"ObjectType\x12\v\n" +
	"\aOBJ_INT\x10\x00\x12\r\n" +
	"\tOBJ_FLOAT\x10\x01\x12\f\n" +
	"\bOBJ_BOOL\x10\x02\x12\v\n" +
	"\aOBJ_NIL\x10\x03\x12\x0e\n" +
	"\n" +
	"OBJ_STRING\x10\x04\x12\x10\n" +
	"\fOBJ_FUNCTION\x10\x05\x12\x0f\n" +
	"\vOBJ_CLOSURE\x10\x06B\x04Z\x02./b\x06proto3"

var (
	file_object_proto_rawDescOnce sync.Once
	file_object_proto_rawDescData []byte
)

func file_object_proto_rawDescGZIP() []byte {
	file_object_proto_rawDescOnce.Do(func() {
		file_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)))
	})
	return file_object_proto_rawDescData
}

var file_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_object_proto_goTypes = []any{
	(ObjectType)(0),  // 0: Object.ObjectType
	(*Function)(nil), // 1: Object.Function
	(*Closure)(nil),  // 2: Object.Closure
	(*Object)(nil),   // 3: Object.Object
	(*Chunk)(nil),    // 4: Object.Chunk
}
var file_object_proto_depIdxs = []int32{
	1, // 0: Object.Closure.function:type_name -> Object.Function
	0, // 1: Object.Object.object_type:type_name -> Object.ObjectType
	1, // 2: Object.Object.literal_function:type_name -> Object.Function
	2, // 3: Object.Object.literal_closure:type_name -> Object.Closure
	1, // 4: Object.Chunk.function:type_name -> Object.Function
	3, // 5: Object.Chunk.constants:type_name -> Object.Object
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_object_proto_init() }
func file_object_proto_init() {
	if File_object_proto != nil {
		return
	}
	file_object_proto_msgTypes[2].OneofWrappers = []any{
		(*Object_LiteralInt)(nil),
		(*Object_LiteralFloat)(nil),
		(*Object_LiteralBool)(nil),
		(*Object_LiteralNil)(nil),
		(*Object_LiteralString)(nil),
		(*Object_LiteralFunction)(nil),
		(*Object_LiteralClosure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_proto_goTypes,
		DependencyIndexes: file_object_proto_depIdxs,
		EnumInfos:         file_object_proto_enumTypes,
		MessageInfos:      file_object_proto_msgTypes,
	}.Build()
	File_object_proto = out.File
	file_object_proto_goTypes = nil
	file_object_proto_depIdxs = nil
}
