// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: object.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJ_INT   ObjectType = 0
	ObjectType_OBJ_FLOAT ObjectType = 1
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJ_INT",
		1: "OBJ_FLOAT",
	}
	ObjectType_value = map[string]int32{
		"OBJ_INT":   0,
		"OBJ_FLOAT": 1,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_object_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_object_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

type Object struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ObjectType ObjectType             `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=Object.ObjectType" json:"object_type,omitempty"`
	// Types that are valid to be assigned to Literal:
	//
	//	*Object_LiteralInt
	//	*Object_LiteralFloat
	Literal       isObject_Literal `protobuf_oneof:"literal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_OBJ_INT
}

func (x *Object) GetLiteral() isObject_Literal {
	if x != nil {
		return x.Literal
	}
	return nil
}

func (x *Object) GetLiteralInt() int64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralInt); ok {
			return x.LiteralInt
		}
	}
	return 0
}

func (x *Object) GetLiteralFloat() float64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralFloat); ok {
			return x.LiteralFloat
		}
	}
	return 0
}

type isObject_Literal interface {
	isObject_Literal()
}

type Object_LiteralInt struct {
	LiteralInt int64 `protobuf:"varint,2,opt,name=literal_int,json=literalInt,proto3,oneof"`
}

type Object_LiteralFloat struct {
	LiteralFloat float64 `protobuf:"fixed64,3,opt,name=literal_float,json=literalFloat,proto3,oneof"`
}

func (*Object_LiteralInt) isObject_Literal() {}

func (*Object_LiteralFloat) isObject_Literal() {}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Constants     []*Object              `protobuf:"bytes,2,rep,name=constants,proto3" json:"constants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Chunk) GetConstants() []*Object {
	if x != nil {
		return x.Constants
	}
	return nil
}

var File_object_proto protoreflect.FileDescriptor

const file_object_proto_rawDesc = "" +
	"\n" +
	"\fobject.proto\x12\x06Object\"\x92\x01\n" +
	"\x06Object\x123\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x12.Object.ObjectTypeR\n" +
	"objectType\x12!\n" +
	"\vliteral_int\x18\x02 \x01(\x03H\x00R\n" +
	"literalInt\x12%\n" +
	"\rliteral_float\x18\x03 \x01(\x01H\x00R\fliteralFloatB\t\n" +
	"\aliteral\"I\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04code\x12,\n" +
	"\tconstants\x18\x02 \x03(\v2\x0e.Object.ObjectR\tconstants*(\n" +
	"\n" +
	"ObjectType\x12\v\n" +
	"\aOBJ_INT\x10\x00\x12\r\n" +
	"\tOBJ_FLOAT\x10\x01B\x04Z\x02./b\x06proto3"

var (
	file_object_proto_rawDescOnce sync.Once
	file_object_proto_rawDescData []byte
)

func file_object_proto_rawDescGZIP() []byte {
	file_object_proto_rawDescOnce.Do(func() {
		file_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)))
	})
	return file_object_proto_rawDescData
}

var file_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_object_proto_goTypes = []any{
	(ObjectType)(0), // 0: Object.ObjectType
	(*Object)(nil),  // 1: Object.Object
	(*Chunk)(nil),   // 2: Object.Chunk
}
var file_object_proto_depIdxs = []int32{
	0, // 0: Object.Object.object_type:type_name -> Object.ObjectType
	1, // 1: Object.Chunk.constants:type_name -> Object.Object
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_object_proto_init() }
func file_object_proto_init() {
	if File_object_proto != nil {
		return
	}
	file_object_proto_msgTypes[0].OneofWrappers = []any{
		(*Object_LiteralInt)(nil),
		(*Object_LiteralFloat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_proto_goTypes,
		DependencyIndexes: file_object_proto_depIdxs,
		EnumInfos:         file_object_proto_enumTypes,
		MessageInfos:      file_object_proto_msgTypes,
	}.Build()
	File_object_proto = out.File
	file_object_proto_goTypes = nil
	file_object_proto_depIdxs = nil
}
