// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: object.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	NumParams     uint64                 `protobuf:"varint,2,opt,name=num_params,json=numParams,proto3" json:"num_params,omitempty"`
	NumUpvalues   uint64                 `protobuf:"varint,3,opt,name=num_upvalues,json=numUpvalues,proto3" json:"num_upvalues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Function) GetNumParams() uint64 {
	if x != nil {
		return x.NumParams
	}
	return 0
}

func (x *Function) GetNumUpvalues() uint64 {
	if x != nil {
		return x.NumUpvalues
	}
	return 0
}

type Closure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Upvalues      []*Object              `protobuf:"bytes,2,rep,name=upvalues,proto3" json:"upvalues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Closure) Reset() {
	*x = Closure{}
	mi := &file_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Closure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Closure) ProtoMessage() {}

func (x *Closure) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Closure.ProtoReflect.Descriptor instead.
func (*Closure) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{1}
}

func (x *Closure) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Closure) GetUpvalues() []*Object {
	if x != nil {
		return x.Upvalues
	}
	return nil
}

type Object struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RefCount uint64                 `protobuf:"varint,1,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	// Types that are valid to be assigned to Literal:
	//
	//	*Object_LiteralInt
	//	*Object_LiteralFloat
	//	*Object_LiteralBool
	//	*Object_LiteralNil
	//	*Object_LiteralString
	//	*Object_LiteralFunction
	//	*Object_LiteralClosure
	Literal       isObject_Literal `protobuf_oneof:"literal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetRefCount() uint64 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *Object) GetLiteral() isObject_Literal {
	if x != nil {
		return x.Literal
	}
	return nil
}

func (x *Object) GetLiteralInt() int64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralInt); ok {
			return x.LiteralInt
		}
	}
	return 0
}

func (x *Object) GetLiteralFloat() float64 {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralFloat); ok {
			return x.LiteralFloat
		}
	}
	return 0
}

func (x *Object) GetLiteralBool() bool {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralBool); ok {
			return x.LiteralBool
		}
	}
	return false
}

func (x *Object) GetLiteralNil() string {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralNil); ok {
			return x.LiteralNil
		}
	}
	return ""
}

func (x *Object) GetLiteralString() string {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralString); ok {
			return x.LiteralString
		}
	}
	return ""
}

func (x *Object) GetLiteralFunction() *Function {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralFunction); ok {
			return x.LiteralFunction
		}
	}
	return nil
}

func (x *Object) GetLiteralClosure() *Closure {
	if x != nil {
		if x, ok := x.Literal.(*Object_LiteralClosure); ok {
			return x.LiteralClosure
		}
	}
	return nil
}

type isObject_Literal interface {
	isObject_Literal()
}

type Object_LiteralInt struct {
	LiteralInt int64 `protobuf:"varint,2,opt,name=literal_int,json=literalInt,proto3,oneof"`
}

type Object_LiteralFloat struct {
	LiteralFloat float64 `protobuf:"fixed64,3,opt,name=literal_float,json=literalFloat,proto3,oneof"`
}

type Object_LiteralBool struct {
	LiteralBool bool `protobuf:"varint,4,opt,name=literal_bool,json=literalBool,proto3,oneof"`
}

type Object_LiteralNil struct {
	LiteralNil string `protobuf:"bytes,5,opt,name=literal_nil,json=literalNil,proto3,oneof"`
}

type Object_LiteralString struct {
	LiteralString string `protobuf:"bytes,6,opt,name=literal_string,json=literalString,proto3,oneof"`
}

type Object_LiteralFunction struct {
	LiteralFunction *Function `protobuf:"bytes,7,opt,name=literal_function,json=literalFunction,proto3,oneof"`
}

type Object_LiteralClosure struct {
	LiteralClosure *Closure `protobuf:"bytes,8,opt,name=literal_closure,json=literalClosure,proto3,oneof"`
}

func (*Object_LiteralInt) isObject_Literal() {}

func (*Object_LiteralFloat) isObject_Literal() {}

func (*Object_LiteralBool) isObject_Literal() {}

func (*Object_LiteralNil) isObject_Literal() {}

func (*Object_LiteralString) isObject_Literal() {}

func (*Object_LiteralFunction) isObject_Literal() {}

func (*Object_LiteralClosure) isObject_Literal() {}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closure       *Closure               `protobuf:"bytes,1,opt,name=closure,proto3" json:"closure,omitempty"`
	Constants     []*Object              `protobuf:"bytes,2,rep,name=constants,proto3" json:"constants,omitempty"`
	GlobalsCount  uint64                 `protobuf:"varint,3,opt,name=globals_count,json=globalsCount,proto3" json:"globals_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetClosure() *Closure {
	if x != nil {
		return x.Closure
	}
	return nil
}

func (x *Chunk) GetConstants() []*Object {
	if x != nil {
		return x.Constants
	}
	return nil
}

func (x *Chunk) GetGlobalsCount() uint64 {
	if x != nil {
		return x.GlobalsCount
	}
	return 0
}

var File_object_proto protoreflect.FileDescriptor

const file_object_proto_rawDesc = "" +
	"\n" +
	"\fobject.proto\x12\x06Object\"`\n" +
	"\bFunction\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04code\x12\x1d\n" +
	"\n" +
	"num_params\x18\x02 \x01(\x04R\tnumParams\x12!\n" +
	"\fnum_upvalues\x18\x03 \x01(\x04R\vnumUpvalues\"c\n" +
	"\aClosure\x12,\n" +
	"\bfunction\x18\x01 \x01(\v2\x10.Object.FunctionR\bfunction\x12*\n" +
	"\bupvalues\x18\x02 \x03(\v2\x0e.Object.ObjectR\bupvalues\"\xe6\x02\n" +
	"\x06Object\x12\x1b\n" +
	"\tref_count\x18\x01 \x01(\x04R\brefCount\x12!\n" +
	"\vliteral_int\x18\x02 \x01(\x03H\x00R\n" +
	"literalInt\x12%\n" +
	"\rliteral_float\x18\x03 \x01(\x01H\x00R\fliteralFloat\x12#\n" +
	"\fliteral_bool\x18\x04 \x01(\bH\x00R\vliteralBool\x12!\n" +
	"\vliteral_nil\x18\x05 \x01(\tH\x00R\n" +
	"literalNil\x12'\n" +
	"\x0eliteral_string\x18\x06 \x01(\tH\x00R\rliteralString\x12=\n" +
	"\x10literal_function\x18\a \x01(\v2\x10.Object.FunctionH\x00R\x0fliteralFunction\x12:\n" +
	"\x0fliteral_closure\x18\b \x01(\v2\x0f.Object.ClosureH\x00R\x0eliteralClosureB\t\n" +
	"\aliteral\"\x85\x01\n" +
	"\x05Chunk\x12)\n" +
	"\aclosure\x18\x01 \x01(\v2\x0f.Object.ClosureR\aclosure\x12,\n" +
	"\tconstants\x18\x02 \x03(\v2\x0e.Object.ObjectR\tconstants\x12#\n" +
	"\rglobals_count\x18\x03 \x01(\x04R\fglobalsCountB\x04Z\x02./b\x06proto3"

var (
	file_object_proto_rawDescOnce sync.Once
	file_object_proto_rawDescData []byte
)

func file_object_proto_rawDescGZIP() []byte {
	file_object_proto_rawDescOnce.Do(func() {
		file_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)))
	})
	return file_object_proto_rawDescData
}

var file_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_object_proto_goTypes = []any{
	(*Function)(nil), // 0: Object.Function
	(*Closure)(nil),  // 1: Object.Closure
	(*Object)(nil),   // 2: Object.Object
	(*Chunk)(nil),    // 3: Object.Chunk
}
var file_object_proto_depIdxs = []int32{
	0, // 0: Object.Closure.function:type_name -> Object.Function
	2, // 1: Object.Closure.upvalues:type_name -> Object.Object
	0, // 2: Object.Object.literal_function:type_name -> Object.Function
	1, // 3: Object.Object.literal_closure:type_name -> Object.Closure
	1, // 4: Object.Chunk.closure:type_name -> Object.Closure
	2, // 5: Object.Chunk.constants:type_name -> Object.Object
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_object_proto_init() }
func file_object_proto_init() {
	if File_object_proto != nil {
		return
	}
	file_object_proto_msgTypes[2].OneofWrappers = []any{
		(*Object_LiteralInt)(nil),
		(*Object_LiteralFloat)(nil),
		(*Object_LiteralBool)(nil),
		(*Object_LiteralNil)(nil),
		(*Object_LiteralString)(nil),
		(*Object_LiteralFunction)(nil),
		(*Object_LiteralClosure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_object_proto_rawDesc), len(file_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_proto_goTypes,
		DependencyIndexes: file_object_proto_depIdxs,
		MessageInfos:      file_object_proto_msgTypes,
	}.Build()
	File_object_proto = out.File
	file_object_proto_goTypes = nil
	file_object_proto_depIdxs = nil
}
